//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Modules.Major.Contents.Modules.Major.TemplateReports {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("BaoCaoTongHopDoDac04")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class BaoCaoTongHopDoDac04 : global::System.Data.DataSet {
        
        private BaoCaoTongHopDoDac04DataTable tableBaoCaoTongHopDoDac04;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public BaoCaoTongHopDoDac04() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected BaoCaoTongHopDoDac04(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["BaoCaoTongHopDoDac04"] != null)) {
                    base.Tables.Add(new BaoCaoTongHopDoDac04DataTable(ds.Tables["BaoCaoTongHopDoDac04"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public BaoCaoTongHopDoDac04DataTable _BaoCaoTongHopDoDac04 {
            get {
                return this.tableBaoCaoTongHopDoDac04;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            BaoCaoTongHopDoDac04 cln = ((BaoCaoTongHopDoDac04)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["BaoCaoTongHopDoDac04"] != null)) {
                    base.Tables.Add(new BaoCaoTongHopDoDac04DataTable(ds.Tables["BaoCaoTongHopDoDac04"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableBaoCaoTongHopDoDac04 = ((BaoCaoTongHopDoDac04DataTable)(base.Tables["BaoCaoTongHopDoDac04"]));
            if ((initTable == true)) {
                if ((this.tableBaoCaoTongHopDoDac04 != null)) {
                    this.tableBaoCaoTongHopDoDac04.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void InitClass() {
            this.DataSetName = "BaoCaoTongHopDoDac04";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/BaoCaoTongHopDoDac04.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableBaoCaoTongHopDoDac04 = new BaoCaoTongHopDoDac04DataTable();
            base.Tables.Add(this.tableBaoCaoTongHopDoDac04);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private bool ShouldSerialize_BaoCaoTongHopDoDac04() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            BaoCaoTongHopDoDac04 ds = new BaoCaoTongHopDoDac04();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public delegate void BaoCaoTongHopDoDac04RowChangeEventHandler(object sender, BaoCaoTongHopDoDac04RowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class BaoCaoTongHopDoDac04DataTable : global::System.Data.TypedTableBase<BaoCaoTongHopDoDac04Row> {
            
            private global::System.Data.DataColumn columnUnionName;
            
            private global::System.Data.DataColumn columnContractNoInfo;
            
            private global::System.Data.DataColumn columnConfirmOn;
            
            private global::System.Data.DataColumn columnCompletedOn;
            
            private global::System.Data.DataColumn columnCusName;
            
            private global::System.Data.DataColumn columnPurposeName;
            
            private global::System.Data.DataColumn columnLandParcelNo;
            
            private global::System.Data.DataColumn columnMapNo;
            
            private global::System.Data.DataColumn columnAddress;
            
            private global::System.Data.DataColumn columnWardName;
            
            private global::System.Data.DataColumn columnProvinceName;
            
            private global::System.Data.DataColumn columnTaskIdx;
            
            private global::System.Data.DataColumn columnTaskName;
            
            private global::System.Data.DataColumn columnDeptHandleTask;
            
            private global::System.Data.DataColumn columnTaskCreatedOn;
            
            private global::System.Data.DataColumn columnTaskCompletedOn;
            
            private global::System.Data.DataColumn columnMeasureHandler;
            
            private global::System.Data.DataColumn columnMeasureDept;
            
            private global::System.Data.DataColumn columnMeasureCompletedOn;
            
            private global::System.Data.DataColumn columnExpertiseHandler;
            
            private global::System.Data.DataColumn columnExpertiseCompletedOn;
            
            private global::System.Data.DataColumn columnSignCreatedOn;
            
            private global::System.Data.DataColumn columnSignCompletedOn;
            
            private global::System.Data.DataColumn columnStatusName;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public BaoCaoTongHopDoDac04DataTable() {
                this.TableName = "BaoCaoTongHopDoDac04";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal BaoCaoTongHopDoDac04DataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected BaoCaoTongHopDoDac04DataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn UnionNameColumn {
                get {
                    return this.columnUnionName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ContractNoInfoColumn {
                get {
                    return this.columnContractNoInfo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ConfirmOnColumn {
                get {
                    return this.columnConfirmOn;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn CompletedOnColumn {
                get {
                    return this.columnCompletedOn;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn CusNameColumn {
                get {
                    return this.columnCusName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn PurposeNameColumn {
                get {
                    return this.columnPurposeName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn LandParcelNoColumn {
                get {
                    return this.columnLandParcelNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn MapNoColumn {
                get {
                    return this.columnMapNo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn AddressColumn {
                get {
                    return this.columnAddress;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn WardNameColumn {
                get {
                    return this.columnWardName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ProvinceNameColumn {
                get {
                    return this.columnProvinceName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn TaskIdxColumn {
                get {
                    return this.columnTaskIdx;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn TaskNameColumn {
                get {
                    return this.columnTaskName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn DeptHandleTaskColumn {
                get {
                    return this.columnDeptHandleTask;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn TaskCreatedOnColumn {
                get {
                    return this.columnTaskCreatedOn;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn TaskCompletedOnColumn {
                get {
                    return this.columnTaskCompletedOn;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn MeasureHandlerColumn {
                get {
                    return this.columnMeasureHandler;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn MeasureDeptColumn {
                get {
                    return this.columnMeasureDept;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn MeasureCompletedOnColumn {
                get {
                    return this.columnMeasureCompletedOn;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ExpertiseHandlerColumn {
                get {
                    return this.columnExpertiseHandler;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ExpertiseCompletedOnColumn {
                get {
                    return this.columnExpertiseCompletedOn;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn SignCreatedOnColumn {
                get {
                    return this.columnSignCreatedOn;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn SignCompletedOnColumn {
                get {
                    return this.columnSignCompletedOn;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn StatusNameColumn {
                get {
                    return this.columnStatusName;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public BaoCaoTongHopDoDac04Row this[int index] {
                get {
                    return ((BaoCaoTongHopDoDac04Row)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event BaoCaoTongHopDoDac04RowChangeEventHandler BaoCaoTongHopDoDac04RowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event BaoCaoTongHopDoDac04RowChangeEventHandler BaoCaoTongHopDoDac04RowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event BaoCaoTongHopDoDac04RowChangeEventHandler BaoCaoTongHopDoDac04RowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event BaoCaoTongHopDoDac04RowChangeEventHandler BaoCaoTongHopDoDac04RowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void AddBaoCaoTongHopDoDac04Row(BaoCaoTongHopDoDac04Row row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public BaoCaoTongHopDoDac04Row AddBaoCaoTongHopDoDac04Row(
                        string UnionName, 
                        string ContractNoInfo, 
                        string ConfirmOn, 
                        string CompletedOn, 
                        string CusName, 
                        string PurposeName, 
                        string LandParcelNo, 
                        string MapNo, 
                        string Address, 
                        string WardName, 
                        string ProvinceName, 
                        string TaskIdx, 
                        string TaskName, 
                        string DeptHandleTask, 
                        string TaskCreatedOn, 
                        string TaskCompletedOn, 
                        string MeasureHandler, 
                        string MeasureDept, 
                        string MeasureCompletedOn, 
                        string ExpertiseHandler, 
                        string ExpertiseCompletedOn, 
                        string SignCreatedOn, 
                        string SignCompletedOn, 
                        string StatusName) {
                BaoCaoTongHopDoDac04Row rowBaoCaoTongHopDoDac04Row = ((BaoCaoTongHopDoDac04Row)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        UnionName,
                        ContractNoInfo,
                        ConfirmOn,
                        CompletedOn,
                        CusName,
                        PurposeName,
                        LandParcelNo,
                        MapNo,
                        Address,
                        WardName,
                        ProvinceName,
                        TaskIdx,
                        TaskName,
                        DeptHandleTask,
                        TaskCreatedOn,
                        TaskCompletedOn,
                        MeasureHandler,
                        MeasureDept,
                        MeasureCompletedOn,
                        ExpertiseHandler,
                        ExpertiseCompletedOn,
                        SignCreatedOn,
                        SignCompletedOn,
                        StatusName};
                rowBaoCaoTongHopDoDac04Row.ItemArray = columnValuesArray;
                this.Rows.Add(rowBaoCaoTongHopDoDac04Row);
                return rowBaoCaoTongHopDoDac04Row;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                BaoCaoTongHopDoDac04DataTable cln = ((BaoCaoTongHopDoDac04DataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new BaoCaoTongHopDoDac04DataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal void InitVars() {
                this.columnUnionName = base.Columns["UnionName"];
                this.columnContractNoInfo = base.Columns["ContractNoInfo"];
                this.columnConfirmOn = base.Columns["ConfirmOn"];
                this.columnCompletedOn = base.Columns["CompletedOn"];
                this.columnCusName = base.Columns["CusName"];
                this.columnPurposeName = base.Columns["PurposeName"];
                this.columnLandParcelNo = base.Columns["LandParcelNo"];
                this.columnMapNo = base.Columns["MapNo"];
                this.columnAddress = base.Columns["Address"];
                this.columnWardName = base.Columns["WardName"];
                this.columnProvinceName = base.Columns["ProvinceName"];
                this.columnTaskIdx = base.Columns["TaskIdx"];
                this.columnTaskName = base.Columns["TaskName"];
                this.columnDeptHandleTask = base.Columns["DeptHandleTask"];
                this.columnTaskCreatedOn = base.Columns["TaskCreatedOn"];
                this.columnTaskCompletedOn = base.Columns["TaskCompletedOn"];
                this.columnMeasureHandler = base.Columns["MeasureHandler"];
                this.columnMeasureDept = base.Columns["MeasureDept"];
                this.columnMeasureCompletedOn = base.Columns["MeasureCompletedOn"];
                this.columnExpertiseHandler = base.Columns["ExpertiseHandler"];
                this.columnExpertiseCompletedOn = base.Columns["ExpertiseCompletedOn"];
                this.columnSignCreatedOn = base.Columns["SignCreatedOn"];
                this.columnSignCompletedOn = base.Columns["SignCompletedOn"];
                this.columnStatusName = base.Columns["StatusName"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            private void InitClass() {
                this.columnUnionName = new global::System.Data.DataColumn("UnionName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUnionName);
                this.columnContractNoInfo = new global::System.Data.DataColumn("ContractNoInfo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnContractNoInfo);
                this.columnConfirmOn = new global::System.Data.DataColumn("ConfirmOn", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnConfirmOn);
                this.columnCompletedOn = new global::System.Data.DataColumn("CompletedOn", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCompletedOn);
                this.columnCusName = new global::System.Data.DataColumn("CusName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCusName);
                this.columnPurposeName = new global::System.Data.DataColumn("PurposeName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPurposeName);
                this.columnLandParcelNo = new global::System.Data.DataColumn("LandParcelNo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLandParcelNo);
                this.columnMapNo = new global::System.Data.DataColumn("MapNo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMapNo);
                this.columnAddress = new global::System.Data.DataColumn("Address", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAddress);
                this.columnWardName = new global::System.Data.DataColumn("WardName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnWardName);
                this.columnProvinceName = new global::System.Data.DataColumn("ProvinceName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnProvinceName);
                this.columnTaskIdx = new global::System.Data.DataColumn("TaskIdx", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTaskIdx);
                this.columnTaskName = new global::System.Data.DataColumn("TaskName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTaskName);
                this.columnDeptHandleTask = new global::System.Data.DataColumn("DeptHandleTask", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDeptHandleTask);
                this.columnTaskCreatedOn = new global::System.Data.DataColumn("TaskCreatedOn", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTaskCreatedOn);
                this.columnTaskCompletedOn = new global::System.Data.DataColumn("TaskCompletedOn", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTaskCompletedOn);
                this.columnMeasureHandler = new global::System.Data.DataColumn("MeasureHandler", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMeasureHandler);
                this.columnMeasureDept = new global::System.Data.DataColumn("MeasureDept", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMeasureDept);
                this.columnMeasureCompletedOn = new global::System.Data.DataColumn("MeasureCompletedOn", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMeasureCompletedOn);
                this.columnExpertiseHandler = new global::System.Data.DataColumn("ExpertiseHandler", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExpertiseHandler);
                this.columnExpertiseCompletedOn = new global::System.Data.DataColumn("ExpertiseCompletedOn", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExpertiseCompletedOn);
                this.columnSignCreatedOn = new global::System.Data.DataColumn("SignCreatedOn", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSignCreatedOn);
                this.columnSignCompletedOn = new global::System.Data.DataColumn("SignCompletedOn", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSignCompletedOn);
                this.columnStatusName = new global::System.Data.DataColumn("StatusName", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnStatusName);
                this.ExtendedProperties.Add("Generator_TablePropName", "_BaoCaoTongHopDoDac04");
                this.ExtendedProperties.Add("Generator_UserTableName", "BaoCaoTongHopDoDac04");
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public BaoCaoTongHopDoDac04Row NewBaoCaoTongHopDoDac04Row() {
                return ((BaoCaoTongHopDoDac04Row)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new BaoCaoTongHopDoDac04Row(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(BaoCaoTongHopDoDac04Row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.BaoCaoTongHopDoDac04RowChanged != null)) {
                    this.BaoCaoTongHopDoDac04RowChanged(this, new BaoCaoTongHopDoDac04RowChangeEvent(((BaoCaoTongHopDoDac04Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.BaoCaoTongHopDoDac04RowChanging != null)) {
                    this.BaoCaoTongHopDoDac04RowChanging(this, new BaoCaoTongHopDoDac04RowChangeEvent(((BaoCaoTongHopDoDac04Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.BaoCaoTongHopDoDac04RowDeleted != null)) {
                    this.BaoCaoTongHopDoDac04RowDeleted(this, new BaoCaoTongHopDoDac04RowChangeEvent(((BaoCaoTongHopDoDac04Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.BaoCaoTongHopDoDac04RowDeleting != null)) {
                    this.BaoCaoTongHopDoDac04RowDeleting(this, new BaoCaoTongHopDoDac04RowChangeEvent(((BaoCaoTongHopDoDac04Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void RemoveBaoCaoTongHopDoDac04Row(BaoCaoTongHopDoDac04Row row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                BaoCaoTongHopDoDac04 ds = new BaoCaoTongHopDoDac04();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "BaoCaoTongHopDoDac04DataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class BaoCaoTongHopDoDac04Row : global::System.Data.DataRow {
            
            private BaoCaoTongHopDoDac04DataTable tableBaoCaoTongHopDoDac04;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal BaoCaoTongHopDoDac04Row(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableBaoCaoTongHopDoDac04 = ((BaoCaoTongHopDoDac04DataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string UnionName {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.UnionNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'UnionName\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.UnionNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ContractNoInfo {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.ContractNoInfoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ContractNoInfo\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.ContractNoInfoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ConfirmOn {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.ConfirmOnColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ConfirmOn\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.ConfirmOnColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string CompletedOn {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.CompletedOnColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CompletedOn\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.CompletedOnColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string CusName {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.CusNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CusName\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.CusNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string PurposeName {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.PurposeNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PurposeName\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.PurposeNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string LandParcelNo {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.LandParcelNoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LandParcelNo\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.LandParcelNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string MapNo {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.MapNoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MapNo\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.MapNoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string Address {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.AddressColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Address\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.AddressColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string WardName {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.WardNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'WardName\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.WardNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ProvinceName {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.ProvinceNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ProvinceName\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.ProvinceNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string TaskIdx {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.TaskIdxColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TaskIdx\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.TaskIdxColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string TaskName {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.TaskNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TaskName\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.TaskNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string DeptHandleTask {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.DeptHandleTaskColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DeptHandleTask\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.DeptHandleTaskColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string TaskCreatedOn {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.TaskCreatedOnColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TaskCreatedOn\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.TaskCreatedOnColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string TaskCompletedOn {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.TaskCompletedOnColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TaskCompletedOn\' in table \'BaoCaoTongHopDoDac04\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.TaskCompletedOnColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string MeasureHandler {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.MeasureHandlerColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MeasureHandler\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.MeasureHandlerColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string MeasureDept {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.MeasureDeptColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MeasureDept\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.MeasureDeptColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string MeasureCompletedOn {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.MeasureCompletedOnColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MeasureCompletedOn\' in table \'BaoCaoTongHopDoDac04\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.MeasureCompletedOnColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ExpertiseHandler {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.ExpertiseHandlerColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ExpertiseHandler\' in table \'BaoCaoTongHopDoDac04\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.ExpertiseHandlerColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ExpertiseCompletedOn {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.ExpertiseCompletedOnColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ExpertiseCompletedOn\' in table \'BaoCaoTongHopDoDac04\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.ExpertiseCompletedOnColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string SignCreatedOn {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.SignCreatedOnColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SignCreatedOn\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.SignCreatedOnColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string SignCompletedOn {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.SignCompletedOnColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SignCompletedOn\' in table \'BaoCaoTongHopDoDac04\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.SignCompletedOnColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string StatusName {
                get {
                    try {
                        return ((string)(this[this.tableBaoCaoTongHopDoDac04.StatusNameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'StatusName\' in table \'BaoCaoTongHopDoDac04\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableBaoCaoTongHopDoDac04.StatusNameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsUnionNameNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.UnionNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetUnionNameNull() {
                this[this.tableBaoCaoTongHopDoDac04.UnionNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsContractNoInfoNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.ContractNoInfoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetContractNoInfoNull() {
                this[this.tableBaoCaoTongHopDoDac04.ContractNoInfoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsConfirmOnNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.ConfirmOnColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetConfirmOnNull() {
                this[this.tableBaoCaoTongHopDoDac04.ConfirmOnColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsCompletedOnNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.CompletedOnColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetCompletedOnNull() {
                this[this.tableBaoCaoTongHopDoDac04.CompletedOnColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsCusNameNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.CusNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetCusNameNull() {
                this[this.tableBaoCaoTongHopDoDac04.CusNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsPurposeNameNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.PurposeNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetPurposeNameNull() {
                this[this.tableBaoCaoTongHopDoDac04.PurposeNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsLandParcelNoNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.LandParcelNoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetLandParcelNoNull() {
                this[this.tableBaoCaoTongHopDoDac04.LandParcelNoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsMapNoNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.MapNoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetMapNoNull() {
                this[this.tableBaoCaoTongHopDoDac04.MapNoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsAddressNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.AddressColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetAddressNull() {
                this[this.tableBaoCaoTongHopDoDac04.AddressColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsWardNameNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.WardNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetWardNameNull() {
                this[this.tableBaoCaoTongHopDoDac04.WardNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsProvinceNameNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.ProvinceNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetProvinceNameNull() {
                this[this.tableBaoCaoTongHopDoDac04.ProvinceNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTaskIdxNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.TaskIdxColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTaskIdxNull() {
                this[this.tableBaoCaoTongHopDoDac04.TaskIdxColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTaskNameNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.TaskNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTaskNameNull() {
                this[this.tableBaoCaoTongHopDoDac04.TaskNameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsDeptHandleTaskNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.DeptHandleTaskColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetDeptHandleTaskNull() {
                this[this.tableBaoCaoTongHopDoDac04.DeptHandleTaskColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTaskCreatedOnNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.TaskCreatedOnColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTaskCreatedOnNull() {
                this[this.tableBaoCaoTongHopDoDac04.TaskCreatedOnColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTaskCompletedOnNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.TaskCompletedOnColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTaskCompletedOnNull() {
                this[this.tableBaoCaoTongHopDoDac04.TaskCompletedOnColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsMeasureHandlerNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.MeasureHandlerColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetMeasureHandlerNull() {
                this[this.tableBaoCaoTongHopDoDac04.MeasureHandlerColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsMeasureDeptNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.MeasureDeptColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetMeasureDeptNull() {
                this[this.tableBaoCaoTongHopDoDac04.MeasureDeptColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsMeasureCompletedOnNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.MeasureCompletedOnColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetMeasureCompletedOnNull() {
                this[this.tableBaoCaoTongHopDoDac04.MeasureCompletedOnColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsExpertiseHandlerNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.ExpertiseHandlerColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetExpertiseHandlerNull() {
                this[this.tableBaoCaoTongHopDoDac04.ExpertiseHandlerColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsExpertiseCompletedOnNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.ExpertiseCompletedOnColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetExpertiseCompletedOnNull() {
                this[this.tableBaoCaoTongHopDoDac04.ExpertiseCompletedOnColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsSignCreatedOnNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.SignCreatedOnColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetSignCreatedOnNull() {
                this[this.tableBaoCaoTongHopDoDac04.SignCreatedOnColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsSignCompletedOnNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.SignCompletedOnColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetSignCompletedOnNull() {
                this[this.tableBaoCaoTongHopDoDac04.SignCompletedOnColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsStatusNameNull() {
                return this.IsNull(this.tableBaoCaoTongHopDoDac04.StatusNameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetStatusNameNull() {
                this[this.tableBaoCaoTongHopDoDac04.StatusNameColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public class BaoCaoTongHopDoDac04RowChangeEvent : global::System.EventArgs {
            
            private BaoCaoTongHopDoDac04Row eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public BaoCaoTongHopDoDac04RowChangeEvent(BaoCaoTongHopDoDac04Row row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public BaoCaoTongHopDoDac04Row Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591